version: '3'

services:
  mongo:
    image: mongo:5.0
    container_name: mongo_fightclub
    restart: unless-stopped
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:0.54
    container_name: mexpress_fightclub
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
  api:
    container_name: api
    image: fighters-api-img
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - mongo:fighter_db
    restart: on-failure